import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { JavaRandom } from '../src/dice/javaRandom.js';

const here = dirname(fileURLToPath(import.meta.url));
const reference = readFileSync(join(here, 'java-random-reference.tsv'), 'utf8');

/**
 * Vectors generated by a real JVM (see scratchpad RandomRef.java). If these pass, the
 * TypeScript generator is bit-identical to java.util.Random, which is the premise the whole
 * conformance-corpus strategy rests on.
 */
describe('JavaRandom matches java.util.Random', () => {
  const lines = reference
    .split('\n')
    .filter((l) => l.trim().length > 0)
    .map((l) => l.split('\t'));

  it('has reference vectors to check against', () => {
    expect(lines.length).toBeGreaterThan(50);
  });

  for (const [seedText, boundText, valuesText] of lines) {
    const seed = Number(seedText);
    const expected = (valuesText ?? '').split(',').map(Number);

    if (boundText === 'nextInt') {
      it(`nextInt() seed=${seedText}`, () => {
        const rng = new JavaRandom(seed);
        const actual = expected.map(() => rng.nextInt32());
        expect(actual).toEqual(expected);
      });
      continue;
    }

    const bound = Number(boundText);
    it(`nextInt(${bound}) seed=${seedText}`, () => {
      const rng = new JavaRandom(seed);
      const actual = expected.map(() => rng.nextInt(bound));
      expect(actual).toEqual(expected);
    });
  }

  it('rejects non-positive bounds like Java does', () => {
    const rng = new JavaRandom(0);
    expect(() => rng.nextInt(0)).toThrow();
    expect(() => rng.nextInt(-1)).toThrow();
  });
});
