package org.alessio29.savagebot.parsing;

import org.alessio29.savagebot.r2.eval.CommandContext;
import org.alessio29.savagebot.r2.eval.RollInterpreter;
import org.alessio29.savagebot.r2.parse.Parser;
import org.alessio29.savagebot.r2.tree.Statement;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Emits a conformance corpus for the TypeScript port of the dice engine.
 *
 * <p>Each record is {@code seed \t expression \t output}, evaluated with a fresh
 * {@code java.util.Random(seed)}. {@code java.util.Random} is a precisely specified 48-bit LCG,
 * so a faithful TypeScript reimplementation produces bit-identical dice sequences -- which makes
 * the port checkable by byte-equality against this file rather than by inspection.
 *
 * <p>Run with: {@code mvn test-compile exec:java -Dexec.mainClass=... -Dexec.classpathScope=test}
 * or via {@link #main} from an IDE. Output path is argv[0].
 */
public class ConformanceCorpus {

    /**
     * Expressions covering the grammar's surface. Grouped by feature so gaps are visible.
     */
    static final String[] EXPRESSIONS = {
            // --- plain dice ---
            "d4", "d6", "d8", "d10", "d12", "d20", "d100", "d%",
            "2d6", "3d8", "10d10", "1d1",
            // --- arithmetic ---
            "d6+1", "d6-1", "2d6+3", "2d6-3", "d6*2", "d6/2", "(d6+d8)*2",
            "d6+d8+d10", "2d6+2d8-4",
            // --- exploding / acing ---
            "d6!", "2d6!", "d4!", "d10!", "10d6!", "d6!+d4!",
            // --- keep / drop / advantage ---
            "4d6k3", "4d6kl3", "2d20adv1", "2d20dis1", "5d10k2", "5d10kl2",
            // --- success / failure counting ---
            "10d10s7", "10d10f1", "12d10f1s7", "28d6!s10f1", "6d6s5f2",
            // --- target numbers and raises ---
            "d20t15", "d20t15r5", "tn10:2d10!+1", "TN10:2d10!+1", "tn10+:2d10!+1",
            "tr6:s6", "tr6:s10",
            // --- Savage Worlds ---
            "s4", "s6", "s8", "s10", "s12", "s4-2", "s8+2", "s8r6",
            "3s8", "3s8w10", "3s6+2", "s8w4", "s12t5r5",
            "e4", "e6", "e8", "4e6", "2e8+1",
            // --- Fudge / Fate ---
            "dF", "4dF", "4dF+2",
            // --- other systems ---
            "dC", "3w", "5w", "d66", "d666",
            "p20c10", "p10c10h", "p10[2d+2]h",
            "i+2", "i-1",
            "2--12", "3--18",
            // --- bounded expressions ---
            "2d6[3:9]", "d20[5:15]", "(d10!+d8!+d6!)[8:24]",
            // --- repetition and batches ---
            "3xd6", "5xs8", "2x[d6;d8]", "10x3s6+2",
            // --- variables and statements ---
            // NB: input is split on whitespace into separate statements, so an assignment
            // must be written without spaces -- `@a := d6` parses as two broken statements.
            "@a:=d6", "@a:=d6; @a+1", "@a:=2d6;@b:=@a*2;@b+1", "d6; d8; d10",
            // --- mixed with narration ---
            "attack s8 damage 2d6!",
    };

    /** Several seeds per expression, so a port cannot pass by matching one lucky sequence. */
    static final long[] SEEDS = {0L, 1L, 42L, 12345L, 987654321L};

    public static void main(String[] args) throws IOException {
        String out = args.length > 0
                ? args[0]
                : "src/test/resources/conformance-corpus.tsv";
        Files.createDirectories(Paths.get(out).toAbsolutePath().getParent());
        int count = 0;
        try (PrintWriter w = new PrintWriter(
                Files.newBufferedWriter(Paths.get(out), StandardCharsets.UTF_8))) {
            w.println("# seed\texpression\toutput");
            w.println("# Generated by ConformanceCorpus. Oracle for the TypeScript dice engine.");
            w.println("# Output newlines are escaped as \\n, tabs as \\t.");
            for (String expression : EXPRESSIONS) {
                for (long seed : SEEDS) {
                    String output;
                    try {
                        output = evaluate(expression, seed);
                    } catch (Exception e) {
                        output = "<<ERROR>> " + e.getClass().getSimpleName() + ": " + e.getMessage();
                    }
                    w.println(seed + "\t" + expression + "\t" + escape(output));
                    count++;
                }
            }
        }
        System.out.println("wrote " + count + " records to " + out);
    }

    static String evaluate(String expression, long seed) {
        List<Statement> statements = new Parser().parse(new String[]{expression});
        CommandContext context = new CommandContext(new Random(seed));
        return new RollInterpreter(context).run(statements);
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t");
    }

    static List<String[]> load(String path) throws IOException {
        List<String[]> records = new ArrayList<>();
        for (String line : Files.readAllLines(Paths.get(path), StandardCharsets.UTF_8)) {
            if (line.isEmpty() || line.startsWith("#")) continue;
            String[] parts = line.split("\t", 3);
            if (parts.length == 3) records.add(parts);
        }
        return records;
    }
}
